# https://github.com/healeycodes/websocket-benchmarker/

language: python
python:
  - "3.7-dev"

install:
  - pip install -r requirements.txt

script:
  - ls # sanity logging
  - python test_bench.py
