# https://github.com/healeycodes/websocket-benchmarker/
dist: xenial
language: python
python:
  - "3.7-dev"

install:
  - which python && python -v
  - pip install -r requirements.txt

script:
  - ls # sanity logging
  - python test_bench.py
